### ISSUE TITLE
Please remove blowfish usage

### ISSUE THREAD

**Issue by timsnyder** [ploxiln/paramiko-ng#135]
We're seeing blowfish warnings now that cryptography has deprecated it.  I assume it is similar if not the same as https://github.com/paramiko/paramiko/issues/2038.  If I get time, I'll dig into the code and submit a PR.  I see that you mentioned completely removing it in #9.  It's time. :)

**Comment by nathanmetcalf** [comment]
Bump - We are experiencing this too. A fix would be greatly appreciated :)

**Comment by nathanmetcalf** [comment]
Thank you @ploxiln 😄
