### ISSUE TITLE
SSHClient.exec_command() should accept open_channel_timeout kwarg

### ISSUE THREAD

**Issue by harixxxx** [ploxiln/paramiko-ng#146]
Currently the **timeout** argument for **exec_command()** servers as the timeout for opening a new channel as well as the channel's read/write timeout. Apps that use paramiko would typically want read/writes to be blocking. This means **timeout=None** should be specified for exec_command. This has the effect of making the timeout for open_channel() 3600 sec, which is very high.

To be able to reduce timeout for open_channel, exec_command should accept an additional **open_channel_timeout** kwarg. This should default to None to maintain backward compatibility.

**Comment by harixxxx** [comment]
@ploxiln Can one of the maintainers review this pull request?
Unless there is a good reason for having a 1-hour timeout for creating a ssh channel, this should be a useful change.

**Comment by ploxiln** [comment]
> Apps that use paramiko would typically want read/writes to be blocking. This means timeout=None should be specified for exec_command.

Is this true for commands that should finish in a reasonable amount of time? For example, if a command should finish in a few seconds, and you give a timeout of 30 seconds, wouldn't the reading/writing block, and work as normal, until the timeout?

**Comment by harixxxx** [comment]
> Is this true for commands that should finish in a reasonable amount of time? For example, if a command should finish in a few seconds, and you give a timeout of 30 seconds, wouldn't the reading/writing block, and work as normal, until the timeout?

It's hard to come up with a timeout specific to each command. A command to upgrade software can take a long time while a simple command can take less than a second. So our app always passes timeout=None. But just opening the channel should always be quick - that's why it would be great to be able to override the default *open_timeout* of 3600 sec.

**Comment by harixxxx** [comment]
Closing

**Comment by harixxxx** [comment]
Closing
