### ISSUE TITLE
Moving from paramiko to paramiko-ng

### ISSUE THREAD

**Issue by lalithorcrux** [ploxiln/paramiko-ng#51]
Is paramiko-ng backward compatible for someone moving from paramiko to paramiko-ng? SSHClient in paramiko was specifically being used and now we intend to move to paramiko-ng.

**Comment by ploxiln** [comment]
Yes, except for the `disabled_algorithms` option added in [paramiko-2.6.0](http://www.paramiko.org/changelog.html#2.6.0) and the SSHConfigDict added in [paramiko-2.5.0](http://www.paramiko.org/changelog.html#2.5.0) and some new SSHConfig features which were added to the paramiko master branch but not yet released (see the top of the changelog page). Most other bugfixes in 2.5.0 and 2.6.0 were ported over to paramiko-ng.
