### ISSUE TITLE
bug of parsing ed25519 type key

### ISSUE THREAD

**Issue by huashengdun** [ploxiln/paramiko-ng#58]
![Screenshot from 2019-12-05 18-19-21](https://user-images.githubusercontent.com/909962/70226673-30cfb380-178c-11ea-8445-6aa17e2e788e.png)

generate keys
```bash
for t in dsa ecdsa ed25519 rsa; do ssh-keygen -t $t -f id_$t -q -N "" && rm *.pub; done
```
parse.py
```python
import sys
from paramiko import DSSKey, ECDSAKey, Ed25519Key, RSAKey


filenames = sys.argv[1:]
keyclasses = [DSSKey, ECDSAKey, Ed25519Key, RSAKey]


for filename in filenames:
    print('Parsing {}'.format(filename))
    print('='*20)
    for keycls in keyclasses:
        try:
            print(keycls.__name__, end=' ')
            key = keycls(filename=filename)
        except Exception as e:
            print('x')
        else:
            print('√')
        print('-'*20)
    print()

```

**Comment by ploxiln** [comment]
Please do not post a screenshot of plain text, please just post plain text.

Can you log the exception and backtrace for the failed loading of id_ed25519 with Ed25519Key? By the way it depends on the `PyNaCl` python package being installed, which is an _optional_ dependency for paramiko-ng as a whole, so it is not installed/required by default.

**Comment by huashengdun** [comment]
Turns out missing dependency `PyNaCl`.
Works now after it being installed.
