### ISSUE TITLE
Password handling behavior changed with introduction of authentication type detection

### ISSUE THREAD

**Issue by nhorter** [ploxiln/paramiko-ng#87]
In [pull request 16](https://github.com/ploxiln/paramiko-ng/pull/16/) client.py was refactored to detect supported authentication types, however, this subtly changed the behavior around password handling during authentication.

Previously, if a server only supported the keyboard-interactive authentication type, the _transport.auth_password_ method was used and has logic for detecting a timeout of a keyboard-interactive prompt and creating a special handler to send the password to the server.

In the newly factored code the _auth_password_ method is completely bypassed if the password authentication method is not supported by a server, thus preventing sending the password to a server supporting keyboard-interactive, but not password authentication, particularly in a non-interactive environment.

We were relying on this fallback functionality in some scripting and found the behavior change on an upgrade to paramiko-ng. The new behavior is probably desirable for some users, but for our use case it is necessary to have some way to pass a password to a server that supports "keyboard-interactive' but not the "password" authentication type.

I don't have a concrete proposal except for perhaps passing a flag during construction in client.py that would be able to toggle that behavior in the __auth_ method.

**Comment by ploxiln** [comment]
Hmm, I see ... `Transport.auth_password()` also called `auth_interactive()`, and used the password for that, depending on the initial error.

I think we could try to bring that back in a mostly automatic way: just before trying password, if password isn't an allowed type but interactive is, and a password is provided, try to use it for interactive. The risk is that some users provide a password that is used in some cases, but need to manually do the interactive in other cases ... for this maybe it is sufficient to let it retry manual interactive once more at the end.
